server.port=8080

# =========================
# TiDB Cloud Configuration
# =========================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/bismillah?sslMode=VERIFY_IDENTITY

spring.datasource.username=GZAW2X97GuUA98C.root
spring.datasource.password=oV5al2zwJRU9TTwn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Don't execute schema.sql and data.sql
spring.sql.init.mode=never

logging.level.org.springframework.jdbc.core=INFO